const filters = {
    cuisines :[
        'African',
        'American',
        'British',
        'Cajun',
        'Caribbean',
        'Chinese',
        'Eastern European',
        'European',
        'French',
        'German',
        'Greek',
        'Indian',
        'Irish',
        'Italian',
        'Japanese',
        'Jewish',
        'Korean',
        'Latin American',
        'Mediterranean',
        'Mexican',
        'Middle Eastern',
        'Nordic',
        'Southern',
        'Spanish',
        'Thai',
        'Vietnamese'],
    diets :[
        'Dairy Free',
        'Gluten Free',
        'Lacto Vegitarian',
        'Ovo Vegitarian',
        'Vegitarian',
        'Vegan',
        'Keto',
        'Pescitarian',
        'Paleo',
        'Whole 30',
        'Low FODMAP'
    ],
    intolorances :[
        'Dairy',
        'Egg',
        'Gluten',
        'Grain',
        'Peanut',
        'Seafood',
        'Sesame',
        'Shellfish',
        'Soy',
        'Sulfite',
        'Tree Nut',
        'Wheat'
    ],
    types :[
        'main course',
        'side dish',
        'dessert',
        'appetizer',
        'salad',
        'bread',
        'breakfast',
        'soup',
        'beverage',
        'sauce',
        'marinade',
        'fingerfood',
        'snack',
        'drink',
    ]
}

    
    
    export default filters

